spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: journalDB
      auto-index-creation: true



server:
  port: ${PORT:8080}
  servlet:
    context-path: /Journal

springdoc:
  swagger-ui:
    path: /docs