spring:
  data:
    mongodb:
      uri: mongodb+srv://priyanshkumar0077_db_user:UyVF5AWuoczusZ54@cluster0.mjrjkxs.mongodb.net/?appName=Cluster0
      database: journalDB
      auto-index-creation: true



server:
  port: 9081
  servlet:
    context-path: /Journal