spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: journalDB
      auto-index-creation: true
  profiles:
    active: dev


server:
  port: ${PORT:8080}
  #servlet:
   # context-path: /Journal

#logging:
 # level:
  #  root: DEBUG
   # org.springdoc: DEBUG
